from enum import Enum
'''
 * @author Julian Frattini
 * Classes of results to evaluate the runs of the system
'''

class CerecResult(Enum):
  CREATION_SUCCESSFUL = 'CREATION_SUCCESSFUL'
  CREATION_FAILED = 'CREATION_FAILED'
  CREATION_IMPOSSIBLE = 'CREATION_IMPOSSIBLE'
  RECOGNITION_SUCCESSFUL = 'RECOGNITION_SUCCESSFUL'
  RECOGNITION_FAILED = 'RECOGNITION_FAILED'
  RECOGNITION_IMPOSSIBLE = 'RECOGNITION_IMPOSSIBLE'
  DISCARDING_SUCCESSFUL = 'DISCARDING_SUCCESSFUL'
  DISCARDING_FAILED = 'DISCARDING_FAILED'
  DEFLECTION_SUCCESSFUL = 'DEFLECTION_SUCCESSFUL'
  DEFLECTION_FAILED = 'DEFLECTION_FAILED'
  SPECIFICATION_SUCCESSFUL = 'SPECIFICATION_SUCCESSFUL'
  SPECIFICATION_FAILED = 'SPECIFICATION_FAILED'
