import os

# GENERAL PATHS

RESOURCES = os.getcwd() + os.path.sep + "resources"
PATH_INPUT = RESOURCES + os.path.sep + "input"
PATH_OUTPUT = RESOURCES + os.path.sep + "output"

PATH_STUDY_RESULT = PATH_OUTPUT + os.path.sep + "cerec";

PATH_CEREC_DATA = PATH_INPUT + os.path.sep + "cerec";

# PURE TRAIN & TEST DATA (generated by Alessio Ferrari, purified by Julian Frattini)

PATH_PURE = PATH_INPUT + os.path.sep + "pure";
PURE_BLITDRAFT = PATH_PURE + os.path.sep + "blitdraft.json";
PURE_CCTNS = PATH_PURE + os.path.sep + "cctns.json";
PURE_DII = PATH_PURE + os.path.sep + "dii.json";
PURE_EIRENE = PATH_PURE + os.path.sep + "eirene.json";
PURE_EIRENE_FUN = PATH_PURE + os.path.sep + "eirene_fun.json";
PURE_ERTMS = PATH_PURE + os.path.sep + "ertms.json";
PURE_GAMMAJ = PATH_PURE + os.path.sep + "gammaj.json";
PURE_GEMINI = PATH_PURE + os.path.sep + "gemini.json";
PURE_GETREAL= PATH_PURE + os.path.sep + "getreal.json";
PURE_KEEPASS = PATH_PURE + os.path.sep + "keepass.json";
PURE_MICROCARE = PATH_PURE + os.path.sep + "microcare.json";
PURE_PEERING = PATH_PURE + os.path.sep + "peering.json";
PURE_PEPPOL = PATH_PURE + os.path.sep + "peppol.json";
PURE_PHIN = PATH_PURE + os.path.sep + "phin.json";
PURE_QHEADACHE = PATH_PURE + os.path.sep + "qheadache.json";
PURE_TCS = PATH_PURE + os.path.sep + "tcs.json";
PURE_THEMAS = PATH_PURE + os.path.sep + "themas.json";
PURE_VIDEO = PATH_PURE + os.path.sep + "video_search.json";

PURE_COLL = [PURE_BLITDRAFT, PURE_CCTNS, PURE_DII, PURE_EIRENE, PURE_EIRENE_FUN, PURE_ERTMS, PURE_GAMMAJ, PURE_GEMINI, PURE_GETREAL, PURE_KEEPASS, PURE_MICROCARE, PURE_PEERING, PURE_PEPPOL, PURE_PHIN, PURE_QHEADACHE, PURE_TCS, PURE_THEMAS, PURE_VIDEO]

PURE_COLL_min = [PURE_EIRENE_FUN, PURE_ERTMS, PURE_GEMINI]   # for understanding lets start with as min as possible